services:
  indexer:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: deps
    working_dir: /app
    command: [ "npm", "run", "indexer:dev" ]
    env_file:
      - server/.env
    ports:
      - "42069:42069"
      - "8080:8080"
    volumes:
      - ./server:/app
      - /app/node_modules
    healthcheck:
      test: [ "CMD", "node", "-e", "require('http').get('http://localhost:8080/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
