services:
  indexer:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: prod
    command: [ "node", "scripts/run-ponder.mjs", "start" ]
    env_file:
      - server/.env
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "node", "-e", "require('http').get('http://localhost:8080/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - app-network

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    env_file:
      - server/.env
    restart: unless-stopped
    depends_on:
      - indexer
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
